### ISSUE TITLE
ec-debianize raspberry pi 3 raspian stretch pre-empt build error

### ISSUE THREAD

**Issue by TacHuynh** [koppi/mk#10]
I have a raspian lite stretch with realtimepi (https://github.com/guysoft/RealtimePi)
Machinekit running ok.

I want to try the ethercat drive with ec-debianize but there is error when building the package.

pi@realtimepi:~/ec-debianize $ uname -a
Linux realtimepi 4.14.34-rt27-v7 #2 SMP PREEMPT RT Tue Jun 12 19:20:24 UTC 2018 armv7l GNU/Linux

pi@realtimepi:~/ec-debianize $ dpkg-checkbuilddeps
dpkg-checkbuilddeps: error: Unmet build dependencies: linux-headers-4.14.34-rt27-v7 linux-image-4.14.34-rt27-v7

Need help to resolve thhis error.
Thanks,
Tac.

**Comment by koppi** [comment]
Hello @TacHuynh,

sorry for my late reply. - Have you been able to fix this issue by ourself?
