### ISSUE TITLE
lcec RT kernel module

### ISSUE THREAD

**Issue by sirop** [koppi/mk#6]
Hallo.

If I see this:
https://github.com/koppi/mk/blob/master/linuxcnc/configs/koppi-cnc/koppi-cnc.hal#L28

then there must be lcec.ko . I have only userland lib lcec.so .

But I do not succeed to build lcec.ko following your tutorial for Debian wheezy.

Is there an important hook I have overseen?

Thanks.

**Comment by koppi** [comment]
Hello @sirop without showing me the log of your console session, I can only guess, what you have done and what happened so far. Please post a log file of your shell session:

``` bash
$ script session.log
$ # [the commands you have typed in and their output]
$ exit
```

Please post `session.log` then. – This repo only contains some sketchy notes, feel free to improve.

**Comment by sirop** [comment]
Hallo, @koppi .
Thanks for your fast reply.
I made a gist of my build session: https://gist.github.com/sirop/48abcf632c92998ec7da
There are some special signs that slipped in, but it is mostly readable.

I suppose `configure.mk` sets the env variables for the build not quite properly,
as I can see from config.mk:

```
cml@debian-cml2:~$ cd linuxcnc-ethercat/
cml@debian-cml2:~/linuxcnc-ethercat$ more config.mk
make[2]: Entering directory `/home/cml/linuxcnc-ethercat'
COMP = /usr/bin/comp
BUILDSYS =
KERNELDIR = /lib/modules/3.8-1-xenomai.x86-amd64/build
CC = x86_64-linux-gnu-gcc
RTAI =
RTAIDIR =
RTFLAGS = -I. -I/usr/include/xenomai -D_GNU_SOURCE -D_REENTRANT -D__XENO__ -DTHREAD_FLAVOR_ID=2 -DRTAPI -D_GNU_SOURCE -D_FORTIFY_SOURCE=0
KERNELRELEASE =
EXTRA_CFLAGS = -I. -I/usr/include/xenomai -D_GNU_SOURCE -D_REENTRANT -D__XENO__ -DTHREAD_FLAVOR_ID=2 -DRTAPI -D_GNU_SOURCE -D_FORTIFY_SOURCE=0 -D__MODULE__ -mieee-fp  -I/usr/include/linuxcnc -fPIC -g -funwind-tables
USE_RTLIBM =
EMC2_HOME = /usr
RUN_IN_PLACE = no
RTLIBDIR = /usr/lib/linuxcnc/xenomai
LIBDIR = /usr/lib
prefix = /usr
make[2]: Leaving directory `/home/cml/linuxcnc-ethercat'
```

I would try to set all these paths manually in `configure.mk`and then rerun the build.

**Comment by koppi** [comment]
I did a quick scan of your log:

1) https://gist.github.com/sirop/48abcf632c92998ec7da#file-linuxcnc-ethercat_build-log-L184 should be `$ sudo usermod -aG xenomai,kmem cml` in your case.

2) For the missing `lcec.ko`: if the Debian build variant with `dpkg-buildpackage` does not work for you, please try the 'manual' build variant:

``` bash
$ sudo apt-get -y install machinekit-dev
$ git clone https://github.com/sittner/linuxcnc-ethercat
$ make -C linuxcnc-ethercat all
$ sudo make -C linuxcnc-ethercat install
```

and see if you get the `lcec.ko` in this way.

**Comment by sirop** [comment]
`sudo usermod -aG xenomai,kmem cml`  was typed in properly by me, don't get confused by recorded special signs of script session.

I tried out the other way - building from source as you proposed.
You can do:  
`make -C linuxcnc-ethercat configure`  
inbetween in oder to have a look at config.mk which in its turn is included in src/realtime.mk .
So my config.mk is:

```
make[1]: Entering directory `/home/cml/linuxcnc-ethercat'
COMP = /usr/bin/comp
BUILDSYS =
KERNELDIR = /lib/modules/3.8-1-xenomai.x86-amd64/build
CC = x86_64-linux-gnu-gcc
RTAI =
RTAIDIR =
RTFLAGS = -I. -I/usr/include/xenomai -D_GNU_SOURCE -D_REENTRANT -D__XENO__ -DTHREAD_FLAVOR_ID=2 -DRTAPI -D_GNU_SOURCE -D_FORTIFY_SOURCE=0
KERNELRELEASE =
EXTRA_CFLAGS = -I. -I/usr/include/xenomai -D_GNU_SOURCE -D_REENTRANT -D__XENO__ -DTHREAD_FLAVOR_ID=2 -DRTAPI -D_GNU_SOURCE -D_FORTIFY_SOURCE=0 -D__MODULE__ -mieee-fp  -I/usr/include/linuxcnc -fPIC -g -funwind-tables
USE_RTLIBM =
EMC2_HOME = /usr
RUN_IN_PLACE = no
RTLIBDIR = /usr/lib/linuxcnc/xenomai
LIBDIR = /usr/lib
prefix = /usr
make[1]: Leaving directory `/home/cml/linuxcnc-ethercat'
```

`/usr/include/xenomai` contains headers only for xenomai user threads, not xenomai kernel threads.

Could you please publish your config.mk so that we could compare?

**Comment by koppi** [comment]
I just checked `/usr/lib/linuxcnc/xenomai`, it contains the `lcec.so` and no `.ko` files:

``` bash
koppi@x200:/usr/lib/linuxcnc$ find -iname "*.ko"
koppi@x200:/usr/lib/linuxcnc$ find -iname "*.so"|grep lcec
./xenomai/lcec.so
```

I'm not an expert with Xenomai, my setup propably works with Xenomai user threads.
Here's the `config.mk` file of my current setup

``` bash
koppi@x200:~/linuxcnc-ethercat $ cat config.mk 
make[2]: Entering directory '/home/koppi/linuxcnc-ethercat'
BUILDSYS = 
KERNELDIR = /lib/modules/3.8-1-xenomai.x86-amd64/build
CC = x86_64-linux-gnu-gcc
RTAI = 
RTAIDIR = 
RTFLAGS = -I. -I/usr/include/xenomai -D_GNU_SOURCE -D_REENTRANT -D__XENO__ -DTHREAD_FLAVOR_ID=2 -DRTAPI -D_GNU_SOURCE -D_FORTIFY_SOURCE=0
KERNELRELEASE = 
EXTRA_CFLAGS = -I. -I/usr/include/xenomai -D_GNU_SOURCE -D_REENTRANT -D__XENO__ -DTHREAD_FLAVOR_ID=2 -DRTAPI -D_GNU_SOURCE -D_FORTIFY_SOURCE=0 -D__MODULE__ -mieee-fp  -I/usr/include/linuxcnc -fPIC -g -funwind-tables
USE_RTLIBM = 
EMC2_HOME = /usr
RUN_IN_PLACE = no
RTLIBDIR = /usr/lib/linuxcnc/xenomai
LIBDIR = /usr/lib
prefix = /usr
make[2]: Leaving directory '/home/koppi/linuxcnc-ethercat'
```

**Comment by sirop** [comment]
Ok, good to know.  
But how could you then:  
`loadrt lcec`  
load an RT kernel module lcec in https://github.com/koppi/mk/blob/master/linuxcnc/configs/koppi-cnc/koppi-cnc.hal#L28 if you have no lcec.ko ?

**Comment by koppi** [comment]
I think, that the command `loadrt lcec` creates an instance of the file:

``` bash
koppi@x200:/usr/lib/linuxcnc/xenomai$ ldd lcec.so 
    linux-vdso.so.1 (0x00007ffd9f3d8000)
    liblinuxcnchal.so.0 => /usr/lib/liblinuxcnchal.so.0 (0x00007fec4759e000)
    libethercat.so.1 => /usr/lib/libethercat.so.1 (0x00007fec47396000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fec4718e000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fec46de5000)
    liblinuxcnc-pb2++.so.0 => /usr/lib/liblinuxcnc-pb2++.so.0 (0x00007fec46abf000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fec467b4000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fec465b0000)
    libprotobuf.so.9 => /usr/lib/x86_64-linux-gnu/libprotobuf.so.9 (0x00007fec46276000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fec46059000)
    libczmq.so.1 => /usr/lib/x86_64-linux-gnu/libczmq.so.1 (0x00007fec45e0f000)
    libzmq.so.3 => /usr/lib/x86_64-linux-gnu/libzmq.so.3 (0x00007fec45baf000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fec45999000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fec479df000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fec45698000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fec4547d000)
    libsodium.so.13 => /usr/lib/x86_64-linux-gnu/libsodium.so.13 (0x00007fec4522a000)
    libpgm-5.1.so.0 => /usr/lib/libpgm-5.1.so.0 (0x00007fec44fdd000)
```

But I'm not 100% sure about this.

**Comment by koppi** [comment]
Does your current setup contain any linuxcnc specific `.ko` files?

**Comment by koppi** [comment]
I just checked `/lib/modules/3.8-1-xenomai.x86-amd64` for ethercat specific `.ko` files:

``` bash
koppi@x200:/lib/modules/3.8-1-xenomai.x86-amd64$ find|grep etherc
./ethercat
./ethercat/master
./ethercat/master/ec_master.ko
./ethercat/examples
./ethercat/examples/mini
./ethercat/examples/mini/ec_mini.ko
./ethercat/devices
./ethercat/devices/e1000
./ethercat/devices/e1000/ec_e1000.ko
./ethercat/devices/ec_r8169.ko
./ethercat/devices/ec_generic.ko
./ethercat/devices/ec_8139too.ko
./ethercat/devices/ec_e100.ko
./ethercat/devices/e1000e
./ethercat/devices/e1000e/ec_e1000e.ko
```

HTH

**Comment by sirop** [comment]
Ok, so my misunderstanding resulted from the belief that you can load only *_ko_ libs
with `loadrt` command. If it is not the case, I beg your pardon.  

My current setup strangely does not contain any linuxcnc specific *_.ko_ miles.
But I succeeded to build machinekit from source before and that build contained *_.ko_ libs.
For example:

```
~$ sudo find -iname hostmot2.ko
./machinekit/src/objects/xenomai-kernel/3.8-1-xenomai.x86-amd64/hostmot2.ko
./machinekit/rtlib/xenomai-kernel/3.8-1-xenomai.x86-amd64/hostmot2.ko
```

Etherlab installation does not cause any problems or questions in my case.

However, it is strange: src/realtime.mk makes me expect some a *_.ko_ lib for _lcec_.
Maybe, it is worth asking Sascha Ittner about it.
